language: node_js

  env:

    - DATABASE_URL=postgresql://postgres@localhost:5432/users_test

  
  node_js:
   - 12.22.1


before_script:
  - psql -c 'create database users_test;' -U postgres
  - psql -U postgres -d users_test -a -f users.test.sql

services:
  - postgresql